# Replace the text below to customize your site
site_name: 33 DUDU
site_description: Master in Design for Emergent Futures
site_author: QIANYIN DU
copyright: Copyleft 2023 "QIANYIN DU" - GNU Free Documentation License
repo_name: 'Future Hacker progress'
site_url: https://33dudu.github.io/magicreator/
repo_url: 'https://github.com/33dudu/magicreator'


nav:
  - ENTRANCE: 
      - Entrance: index.md 
      - Catalan Modernism: cat.md
  - KNOCK,KNOCK: about/me.md
  - YEAR 01:
      - Term 1:
          - LANDING: term1/01-Landing.md
          - DESIGN STUDIO 01: 
             - BrainshIt: term1/03-Brainshit.md 
             - Intervention 01: term1/Intervention 01.md
             - Intervention 02: term1/Intervention 02.md
             - Collective Stories: term1/Collective Stories.md
             - Term01 Conclusion: term1/Term01 Conclusion.md
          - DOCUMENTING DESIGN: term1/04- Documenting Design.md
          - AOWS: term1/02-Atlas of Weak Signals.md
          - THE MACHINE PARADOX: term1/05- The Machine Paradox.md
          - LIVING WITH YOUR OWN IDEAS: term1/06-Living With Your Own Ideas.md
          - BIOLOGY ZERO: 
              - Notes: term1/07- Biology-Zero.md
              - Genetically Modified Organism: term1/10- G.M.O.md
          - AGRICULTURE ZERO: 
              - Notes: term1/08- Agriculture-Zero.md
              - Grow Magic: term1/11-Grow Magic.md
          - DESIGN WITH OTHERS: term1/09- Design With Others.md
          - EXTENDED INTELLIGENCES: term1/12-Extended Intelligences.md
          - DESIGN DIALOGUES: term1/Design Dialogues.md
      - Term 2:
          - DESIGN STUDIO 02: 
              - BRAINSHIT: term2/01- Design Studio 02.md
              - Intervention 01: term2/Intervention 01.md
              - Term02 Conclusion: term2/Term02 Conclusion.md
          - DESIGNING IN A STATE OF CLIMATE EMERGENCY: term2/02- Designing in a State of Climate Emergency.md
          - DESIGNING WITH COLLECTIVE INTELLIGENCE: term2/03- Designing with Collective Intelligence.md
          - FUTURE TALKS: term2/04- Future Talks.md
          - COMMUNICATING IDEAS: term2/05- Communicating Ideas.md
          - DIGITAL PROTOTYPING FOR DESIGN: 
              - TASK01: term2/TASK01Digital Prototyping for Design.md
              - TASK02: term2/TASK02Digital Prototyping for Design.md
              - MICRO CHALLENGE I: term2/Micro Challenge I.md
              - MICRO CHALLENGE II: term2/Micro Challenge II.md
          - MEASURING THE WORLD: term2/06- Measuring The World.md
          - DESIGNING WITH EXTENDED INTELLIGENCES: term2/07- Designing with Extended Intelligences.md
      - Term 3:
          - DESIGN STUDIO 03: term3/01- Design Studio 03.md
          - FUTURE TALKS: term3/02- Future Talks.md
          - DESIGN ETHICS: term3/03- Design Ethics.md
          - CRITICAL TRANSFEMINIST DESIGN: term3/04- Critical Transfeminist Design.md
          - COMMUNICATING IDEAS: term3/05- Communicating Ideas.md
          - THE ATLAS OF WEAK SIGNALS: term3/06- The Atlas of Weak Signals.md
          - MDEFest 2024: term3/07- MDEFest 2024.md
          - DIGITAL PROTOTYPING FOR DESIGN:
              - TASK03: term3/Task03.md
              - TASK04: term3/Task04.md
              - TASK05: term3/Task05.md
              - MICRO CHALLENGE III: term3/Micro Challenge III.md
  - YEAR 02:
      - Term 1:
          - Fabricademy: 
              - Natural Dyes: term01/Natural Dyes.md
              - Soft Robotics: term01/Soft Robotics.md
          - Research & Methods Workshop: term01/RM workshop.md
          - Ecological Interaction: term01/Ecological Interaction.md
          - Interaction & Prototyping: term01/Interaction Prototyping.md
          - Thesis Project: term01/Thesis Project.md
          - Emerging Economies: term01/Emerging Economies.md
      - Term 2:
          - Research & Methods Workshop 02: term02/RM workshop02.md
          - Thesis Project 02: term02/Thesis project.md
          - Mentorship: term02/Mentorship.md
          - Electronics Design: term02/Electronics design.md
  - MASTER PROJECT:
      - GenTe Art Movement: project/gente.md
      


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/d.q_y/?hl=en/


theme:
  name: material

  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: cyan
  font:
    # See available fonts at https://fonts.google.com/
    text: Changa
    code: VT323 
  logo: images/dudu.png
  favicon: images/dudu.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox:
      zoomable: true
      draggable: true
      skip_classes:
        - skip-lightbox


markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format  
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - tables
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css


